export const reservationStatus = {
    PAID: 'PAID',
    CANCELED: 'CANCELED',
    SCHEDULED: 'SCHEDULED',
    PASTDUE: 'PAST DUE'
};

export const messageTypes = {
    USER_CREATED: 'USER_CREATED',
    RESERVATION_CREATED: 'RESERVATION_CREATED',
    RESERVATION_PAYMENT_RECEIVED: 'RESERVATION_PAYMENT_RECEIVED',
    RESERVATION_STATUS_UPDATED: 'RESERVATION_STATUS_UPDATED',
    GUEST_GAVE_FEEDBACK: 'GUEST_GAVE_FEEDBACK',
    GUEST_UPLOADED_IMAGE: 'GUEST_UPLOADED_IMAGE',
    GUEST_SIGNED_IN: 'GUEST_SIGNED_IN',
    GUEST_SIGNED_OUT: 'GUEST_SIGNED_OUT',
    GUEST_UPDATED_PROFILE: 'GUEST_UPDATED_PROFILE',
    NAVIGATION: 'NAVIGATION',
    NONPAYMENT: 'NONPAYMENT (canceled or errored)'
};
